nemtech/symbol-sdk-java

- src/integration-test/java/io/nem/sdk/infrastructure/AccountHttpTest.java
- src/integration-test/java/io/nem/sdk/infrastructure/BlockchainHttpTest.java
- src/integration-test/java/io/nem/sdk/infrastructure/MosaicHttpTest.java
- src/integration-test/java/io/nem/sdk/infrastructure/NamespaceHttpTest.java
- src/integration-test/java/io/nem/sdk/infrastructure/TransactionHttpTest.java
- src/integration-test/resources/config.properties
- src/main/java/io/nem/sdk/infrastructure/AccountHttp.java
- src/main/java/io/nem/sdk/infrastructure/BlockchainHttp.java
- src/main/java/io/nem/sdk/infrastructure/Http.java
- src/main/java/io/nem/sdk/infrastructure/MosaicHttp.java
- src/main/java/io/nem/sdk/infrastructure/NamespaceHttp.java
- src/main/java/io/nem/sdk/infrastructure/NetworkHttp.java
- src/main/java/io/nem/sdk/infrastructure/TransactionHttp.java
This pull request solves #2. But more steps are required to make the error mapping safe.
> Error handling

- .gitignore
- src/main/java/io/nem/sdk/model/receipt/ArtifactExpiryReceipt.java
- src/main/java/io/nem/sdk/model/receipt/BalanceChangeReceipt.java
- src/main/java/io/nem/sdk/model/receipt/BalanceTransferReceipt.java
- src/main/java/io/nem/sdk/model/receipt/InflationReceipt.java
- src/main/java/io/nem/sdk/model/receipt/Receipt.java
- src/main/java/io/nem/sdk/model/receipt/ReceiptSource.java
- src/main/java/io/nem/sdk/model/receipt/ReceiptType.java
- src/main/java/io/nem/sdk/model/receipt/ReceiptVersion.java
- src/main/java/io/nem/sdk/model/receipt/ResolutionEntry.java
- src/main/java/io/nem/sdk/model/receipt/ResolutionStatement.java
- src/main/java/io/nem/sdk/model/receipt/Statement.java
- src/main/java/io/nem/sdk/model/receipt/TransactionStatement.java
- src/test/java/io/nem/sdk/model/receipt/ArtifactExpiryReceiptTest.java
- src/test/java/io/nem/sdk/model/receipt/BalanceChangeReceiptTest.java
- src/test/java/io/nem/sdk/model/receipt/BalanceTransferReceiptTest.java
- src/test/java/io/nem/sdk/model/receipt/InflationReceiptTest.java
- src/test/java/io/nem/sdk/model/receipt/ReceiptSourceTest.java
- src/test/java/io/nem/sdk/model/receipt/ResolutionEntryTest.java
- src/test/java/io/nem/sdk/model/receipt/ResolutionStatementTest.java
- src/test/java/io/nem/sdk/model/receipt/StatementTest.java
- src/test/java/io/nem/sdk/model/receipt/TransactionStatementTest.java
Issue #48 
Added Receipt models
> Issue #48 receipt

- CONTRIBUTING.md
- resources/GoogleStyle_IntelliJ.xml
Issue #77 
- Added modified google code style xml (modified with 4 spaces on all indentations)
- Updated contribution readme file.
> Google code style sheet

- sdk-core/src/main/java/io/nem/sdk/model/transaction/TransferTransaction.java
- sdk-core/src/test/java/io/nem/sdk/model/transaction/TransferTransactionTest.java
- Sort mosaics (unsigned long value) in TransferTransaction
- Added unit tests
> JAV-62 Sort Mosaics in TransferTransaction

- sdk-core/src/main/java/io/nem/sdk/model/mosaic/NetworkCurrencyMosaic.java
- sdk-core/src/test/java/io/nem/sdk/model/mosaic/NetworkCurrencyMosaicTest.java
> JAVA-77 NetworkCurrencyMosaic createRelative for amount with a decimal point

- build.gradle
It fixes https://github.com/nemtech/nem2-sdk-java/issues/162
> Added UTF-8 encoding to build process

- integration-tests/src/test/java/io/nem/sdk/infrastructure/AggregateTransactionServiceIntegrationTest.java
- sdk-core/src/main/java/io/nem/core/crypto/PublicKey.java
- sdk-core/src/main/java/io/nem/sdk/api/AggregateTransactionService.java
- sdk-core/src/main/java/io/nem/sdk/infrastructure/AggregateTransactionServiceImpl.java
- sdk-core/src/main/java/io/nem/sdk/infrastructure/BinarySerializationImpl.java
- sdk-core/src/main/java/io/nem/sdk/infrastructure/TransactionServiceImpl.java
- sdk-core/src/main/java/io/nem/sdk/model/transaction/Transaction.java
- sdk-core/src/test/java/io/nem/core/crypto/PublicKeyTest.java
- sdk-core/src/test/java/io/nem/sdk/infrastructure/AggregateTransactionServiceTest.java
- sdk-okhttp-client/src/main/java/io/nem/sdk/infrastructure/okhttp/BlockRepositoryOkHttpImpl.java
TS versions for reference:
https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/df4e16e53ed0603dbcc53a505281b4ba847b5f2d/src/service/AggregateTransactionService.ts
> JAVA-87 - AggregateTransactionService and isComplete method

- sdk-core/src/main/java/io/nem/sdk/model/receipt/BalanceTransferReceipt.java
- sdk-core/src/test/java/io/nem/sdk/model/blockchain/BlockDurationTest.java
- sdk-core/src/test/java/io/nem/sdk/model/receipt/BalanceTransferReceiptTest.java
- sdk-core/src/test/java/io/nem/sdk/model/receipt/TransactionStatementTest.java
- sdk-okhttp-client/src/test/java/io/nem/sdk/infrastructure/okhttp/AccountRepositoryOkHttpImplTest.java
- sdk-okhttp-client/src/test/java/io/nem/sdk/infrastructure/okhttp/BlockRepositoryOkHttpImplTest.java
- sdk-okhttp-client/src/test/java/io/nem/sdk/infrastructure/okhttp/MultisigRepositoryOkHttpImplTest.java
- sdk-vertx-client/src/test/java/io/nem/sdk/infrastructure/vertx/AccountRepositoryVertxImplTest.java
- sdk-vertx-client/src/test/java/io/nem/sdk/infrastructure/vertx/BlockRepositoryVertxImplTest.java
- sdk-vertx-client/src/test/java/io/nem/sdk/infrastructure/vertx/MultisigRepositoryVertxImplTest.java
Addresses https://github.com/nemtech/nem2-sdk-java/issues/177
> Fixed JAVA-90 BalanceTransferReceipt invalid serialize

- sdk-core/src/main/java/io/nem/sdk/model/namespace/AliasBase.java
- sdk-core/src/test/java/io/nem/sdk/model/namespace/AliasTest.java
Fixes issue https://github.com/nemtech/nem2-sdk-java/issues/186
> Fixed AliasBase.isEmpty()

- sdk-core/build.gradle
- sdk-core/src/main/java/io/nem/sdk/infrastructure/BinarySerializationImpl.java
- sdk-core/src/main/java/io/nem/sdk/infrastructure/SerializationUtils.java
- sdk-core/src/main/java/io/nem/sdk/model/receipt/ArtifactExpiryReceipt.java
- sdk-core/src/main/java/io/nem/sdk/model/receipt/BalanceChangeReceipt.java
- sdk-core/src/main/java/io/nem/sdk/model/receipt/BalanceTransferReceipt.java
- sdk-core/src/main/java/io/nem/sdk/model/receipt/InflationReceipt.java
- sdk-core/src/main/java/io/nem/sdk/model/receipt/ReceiptSource.java
- sdk-core/src/test/java/io/nem/sdk/model/receipt/ReceiptSourceTest.java
- sdk-core/src/test/java/io/nem/sdk/model/receipt/ReceiptTypeTest.java
- sdk-core/src/test/java/io/nem/sdk/model/transaction/AbstractTransactionTester.java
- sdk-core/src/test/java/io/nem/sdk/model/transaction/AggregateTransactionTest.java
- sdk-core/src/test/java/io/nem/sdk/model/transaction/TransactionTypeTest.java
- sdk-core/src/test/java/io/nem/sdk/model/transaction/TransferTransactionTest.java
- sdk-okhttp-client/src/test/java/io/nem/sdk/infrastructure/okhttp/TransactionMapperSerializationTest.java
- sdk-okhttp-client/src/test/resources/json/TransactionMapping-shouldCreateAggregateAccountMetadataTransaction.json
- sdk-okhttp-client/src/test/resources/json/TransactionMapping-shouldCreateAggregateMosaicMetadataTransaction.json
- sdk-okhttp-client/src/test/resources/json/TransactionMapping-shouldCreateAggregateNamespaceMetadataTransaction.json
- sdk-vertx-client/src/test/java/io/nem/sdk/infrastructure/vertx/TransactionMapperSerializationTest.java
- sdk-vertx-client/src/test/resources/json/TransactionMapping-shouldCreateAggregateAccountMetadataTransaction.json
- sdk-vertx-client/src/test/resources/json/TransactionMapping-shouldCreateAggregateMosaicMetadataTransaction.json
- sdk-vertx-client/src/test/resources/json/TransactionMapping-shouldCreateAggregateNamespaceMetadataTransaction.json
- Fixed aggregate transaction builder
- Fixed entity type dto workaround
- Receipts are serialized using builders
> Updated catbuffer generated lib

- sdk-core/src/test/java/io/nem/sdk/model/transaction/MosaicGlobalRestrictionTransactionTest.java
- sdk-core/src/test/java/io/nem/sdk/model/transaction/NamespaceRegistrationTransactionTest.java
- sdk-okhttp-client/src/main/java/io/nem/sdk/infrastructure/okhttp/TransactionRepositoryOkHttpImpl.java
- sdk-okhttp-client/src/test/java/io/nem/sdk/infrastructure/okhttp/AbstractOkHttpRespositoryTest.java
- sdk-okhttp-client/src/test/java/io/nem/sdk/infrastructure/okhttp/AccountRepositoryOkHttpImplTest.java
- sdk-okhttp-client/src/test/java/io/nem/sdk/infrastructure/okhttp/OkHttpAggregateTransactionTest.java
- sdk-okhttp-client/src/test/java/io/nem/sdk/infrastructure/okhttp/TransactionRepositoryOkHttpImplTest.java
- sdk-vertx-client/src/main/java/io/nem/sdk/infrastructure/vertx/TransactionRepositoryVertxImpl.java
- sdk-vertx-client/src/test/java/io/nem/sdk/infrastructure/vertx/AbstractVertxRespositoryTest.java
- sdk-vertx-client/src/test/java/io/nem/sdk/infrastructure/vertx/TransactionRepositoryVertxImplTest.java
- sdk-vertx-client/src/test/java/io/nem/sdk/infrastructure/vertx/VertxAggregateTransactionTest.java
Fixed https://github.com/nemtech/nem2-sdk-java/issues/193
Improved unit tests
> Unable to cosign a aggregate bonded transaction Fixes #193

- sdk-core/src/main/java/io/nem/sdk/model/message/Message.java
- sdk-okhttp-client/src/main/java/io/nem/sdk/infrastructure/okhttp/JsonSerializationOkHttp.java
- sdk-okhttp-client/src/test/java/io/nem/sdk/infrastructure/okhttp/TransactionMapperOkHttpTest.java
- sdk-okhttp-client/src/test/resources/json/TransactionMapping-shouldCreateTransferEmptyMessage.json
- sdk-vertx-client/src/test/java/io/nem/sdk/infrastructure/vertx/TransactionMapperVertxTest.java
- sdk-vertx-client/src/test/resources/json/TransactionMapping-shouldCreateTransferEmptyMessage.json
Fix of https://github.com/nemtech/nem2-sdk-java/issues/190
> Transfer empty message#190

- integration-tests/src/test/java/io/nem/sdk/infrastructure/TransactionRepositoryIntegrationTest.java
- integration-tests/src/test/java/io/nem/sdk/infrastructure/TransferTransactionIntegrationTest.java
- integration-tests/src/test/resources/config.json
- sdk-core/src/main/java/io/nem/sdk/api/AccountRepository.java
- sdk-core/src/main/java/io/nem/sdk/infrastructure/ListenerBase.java
- sdk-core/src/main/java/io/nem/sdk/model/message/Message.java
- sdk-okhttp-client/src/main/java/io/nem/sdk/infrastructure/okhttp/AccountRepositoryOkHttpImpl.java
- sdk-okhttp-client/src/test/java/io/nem/sdk/infrastructure/okhttp/AccountRepositoryOkHttpImplTest.java
- sdk-okhttp-client/src/test/java/io/nem/sdk/infrastructure/okhttp/ListenerOkHttpTest.java
- sdk-vertx-client/src/main/java/io/nem/sdk/infrastructure/vertx/AccountRepositoryVertxImpl.java
- sdk-vertx-client/src/test/java/io/nem/sdk/infrastructure/vertx/AccountRepositoryVertxImplTest.java
- sdk-vertx-client/src/test/java/io/nem/sdk/infrastructure/vertx/ListenerVertxTest.java
- Added AccountRepository.partialTransactions
- Fixed listener status's code attribute
> Account Repository partial transaction query

- build.gradle
- integration-tests/src/test/resources/config.json
- sdk-core/src/main/java/io/nem/sdk/model/node/RoleType.java
- sdk-okhttp-client/src/test/java/io/nem/sdk/infrastructure/okhttp/EnumMapperTest.java
- sdk-vertx-client/src/test/java/io/nem/sdk/infrastructure/vertx/EnumMapperTest.java
Fixes https://github.com/nemtech/nem2-sdk-java/issues/210
> Update open api version to 0.7.22

- build.gradle
- integration-tests/src/test/java/io/nem/sdk/infrastructure/NetworkRepositoryIntegrationTest.java
- sdk-core/src/main/java/io/nem/sdk/api/NetworkRepository.java
- sdk-core/src/main/java/io/nem/sdk/model/blockchain/NetworkFees.java
- sdk-core/src/test/java/io/nem/sdk/model/blockchain/NetworkFeesTest.java
- sdk-okhttp-client/src/main/java/io/nem/sdk/infrastructure/okhttp/NetworkRepositoryOkHttpImpl.java
- sdk-okhttp-client/src/test/java/io/nem/sdk/infrastructure/okhttp/NetworkRepositoryOkHttpImplTest.java
- sdk-vertx-client/src/main/java/io/nem/sdk/infrastructure/vertx/NetworkRepositoryVertxImpl.java
- sdk-vertx-client/src/test/java/io/nem/sdk/infrastructure/vertx/NetworkRepositoryVertxImplTest.java
Added NetworkRepository getNetworkFees method
> Upgraded repositories to Open api spec 0.8.3

- sdk-core/src/main/java/io/nem/core/crypto/Hashes.java
- sdk-core/src/test/java/io/nem/core/crypto/HashVectorTest.java
- sdk-core/src/test/java/io/nem/core/crypto/HashesTest.java
- sdk-core/src/test/java/io/nem/core/crypto/HashesTypescriptValidationTest.java
Fixes https://github.com/nemtech/nem2-sdk-java/issues/231
> Added KECCAK hashes and hash160 hashes back to Hashes

- integration-tests/build.gradle
- sdk-okhttp-client/build.gradle
- sdk-okhttp-client/src/main/java/io/nem/symbol/sdk/infrastructure/okhttp/JsonHelperGson.java
- sdk-okhttp-client/src/test/java/io/nem/symbol/sdk/infrastructure/okhttp/JsonHelperGsonTest.java
- sdk-vertx-client/build.gradle
- sdk-vertx-client/src/main/java/io/nem/symbol/sdk/infrastructure/vertx/JsonHelperJackson2.java
- sdk-vertx-client/src/test/java/io/nem/symbol/sdk/infrastructure/vertx/JsonHelperJackson2Test.java
Small improvement allowing JDK 8 objects like Optional to be JSON serialized/deserialized
> Added jdk 8 adapters for gson and jackson2

- build.gradle
- travis/release.sh
Removed POST_RELEASE_BRANCH default
> Renamed GRGIT_USER to GITHUB_TOKEN

- sdk-core/src/main/java/io/nem/symbol/core/utils/ConvertUtils.java
- sdk-core/src/test/java/io/nem/symbol/core/utils/ConvertUtilsTest.java
- sdk-core/src/test/java/io/nem/symbol/core/utils/MapperUtilsTest.java
> fixed reverse hex

- sdk-core/src/main/java/io/nem/symbol/sdk/api/BinarySerialization.java
- sdk-core/src/main/java/io/nem/symbol/sdk/infrastructure/BinarySerializationImpl.java
Fixes #277 
I've added an extra method that returns a transaction factory. You can tune the transaction using the factory, including changing/adding the info.
> Added serialize to transaction

- build.gradle
- sdk-core/build.gradle
- sdk-core/src/main/java/io/nem/symbol/sdk/infrastructure/BinarySerializationImpl.java
- sdk-core/src/main/java/io/nem/symbol/sdk/infrastructure/SerializationUtils.java
- sdk-core/src/main/java/io/nem/symbol/sdk/model/receipt/BalanceTransferReceipt.java
- sdk-core/src/main/java/io/nem/symbol/sdk/model/receipt/ResolutionEntry.java
- sdk-core/src/main/java/io/nem/symbol/sdk/model/receipt/ResolutionStatement.java
- sdk-core/src/main/java/io/nem/symbol/sdk/model/transaction/AccountKeyLinkTransaction.java
- sdk-core/src/main/java/io/nem/symbol/sdk/model/transaction/AccountKeyLinkTransactionFactory.java
- sdk-core/src/test/java/io/nem/symbol/sdk/model/message/EncryptedMessageTest.java
- sdk-core/src/test/java/io/nem/symbol/sdk/model/receipt/BalanceTransferReceiptTest.java
- sdk-core/src/test/java/io/nem/symbol/sdk/model/transaction/AccountKeyLinkTransactionTest.java
- sdk-core/src/test/resources/json/transaction-aggregateAccountKeyLinkTransaction.json
- sdk-okhttp-client/src/main/java/io/nem/symbol/sdk/infrastructure/okhttp/ReceiptMappingOkHttp.java
- sdk-okhttp-client/src/main/java/io/nem/symbol/sdk/infrastructure/okhttp/mappers/AccountLinkTransactionMapper.java
- sdk-okhttp-client/src/test/java/io/nem/symbol/sdk/infrastructure/okhttp/TransactionMapperOkHttpTest.java
- sdk-vertx-client/src/main/java/io/nem/symbol/sdk/infrastructure/vertx/ReceiptMappingVertx.java
- sdk-vertx-client/src/main/java/io/nem/symbol/sdk/infrastructure/vertx/mappers/AccountLinkTransactionMapper.java
- sdk-vertx-client/src/test/java/io/nem/symbol/sdk/infrastructure/vertx/TransactionMapperVertxTest.java
> 9.5.1 catbuffer and client patch

- sdk-core/src/main/java/io/nem/symbol/sdk/api/BinarySerialization.java
- sdk-core/src/main/java/io/nem/symbol/sdk/infrastructure/BinarySerializationImpl.java
- sdk-core/src/main/java/io/nem/symbol/sdk/model/transaction/AggregateTransactionFactory.java
- sdk-core/src/main/java/io/nem/symbol/sdk/model/transaction/Transaction.java
- sdk-core/src/main/java/io/nem/symbol/sdk/model/transaction/TransactionFactory.java
- sdk-core/src/test/resources/json/transaction-accountAddressRestrictionTransaction.json
- sdk-core/src/test/resources/json/transaction-aggregateMosaicSupplyChangeTransaction.json
- sdk-core/src/test/resources/json/transaction-standaloneSubNamespaceCreationTransaction.json
- sdk-okhttp-client/src/main/java/io/nem/symbol/sdk/infrastructure/okhttp/mappers/AbstractTransactionMapper.java
- sdk-okhttp-client/src/test/java/io/nem/symbol/sdk/infrastructure/okhttp/TransactionMapperSerializationOkHttpTest.java
- sdk-vertx-client/src/main/java/io/nem/symbol/sdk/infrastructure/vertx/mappers/AbstractTransactionMapper.java
- sdk-vertx-client/src/test/java/io/nem/symbol/sdk/infrastructure/vertx/TransactionMapperSerializationVertxTest.java
- travis/release.sh
Fixes https://github.com/nemtech/symbol-sdk-java/issues/310
> Using size from rest's transaction payload

- build.gradle
- integration-tests/src/test/java/io/nem/symbol/sdk/infrastructure/AccountMetadataIntegrationTest.java
- sdk-core/src/main/java/io/nem/symbol/core/utils/ConvertUtils.java
- sdk-core/src/main/java/io/nem/symbol/sdk/model/network/ChainProperties.java
- sdk-core/src/main/java/io/nem/symbol/sdk/model/transaction/VotingKeyLinkTransactionFactory.java
- sdk-core/src/test/java/io/nem/symbol/core/utils/ConvertUtilsTest.java
- sdk-core/src/test/resources/json/network-configuration.json
- sdk-okhttp-client/src/main/java/io/nem/symbol/sdk/infrastructure/okhttp/NetworkRepositoryOkHttpImpl.java
- sdk-vertx-client/src/main/java/io/nem/symbol/sdk/infrastructure/vertx/NetworkRepositoryVertxImpl.java
Added missing chain properties
> Updated open api to 0.9.4

- sdk-core/src/main/java/io/nem/symbol/sdk/infrastructure/BinarySerializationImpl.java
- sdk-core/src/main/java/io/nem/symbol/sdk/model/transaction/MultisigAccountModificationTransactionFactory.java
- sdk-core/src/test/resources/json/transaction-aggregateAccountMetadataTransaction.json
- sdk-core/src/test/resources/json/transaction-aggregateNamespaceMetadataTransaction.json
- sdk-core/src/test/resources/json/transaction-standaloneMultisigModificationTransaction.json
- sdk-okhttp-client/src/test/java/io/nem/symbol/sdk/infrastructure/okhttp/TransactionMapperOkHttpTest.java
- sdk-vertx-client/src/test/java/io/nem/symbol/sdk/infrastructure/vertx/TransactionMapperVertxTest.java
Fixes https://github.com/nemtech/symbol-sdk-java/issues/321
> Incorrect delta negative validation

- build.gradle
- integration-tests/src/test/java/io/nem/symbol/sdk/infrastructure/ReceiptRepositoryTransactionSearchIntegrationTest.java
- integration-tests/src/test/java/io/nem/symbol/sdk/infrastructure/TransactionRepositoryIntegrationTest.java
- sdk-core/src/main/java/io/nem/symbol/sdk/api/TransactionStatementSearchCriteria.java
- sdk-core/src/test/java/io/nem/symbol/sdk/api/TransactionStatementSearchCriteriaTest.java
- sdk-okhttp-client/src/main/java/io/nem/symbol/sdk/infrastructure/okhttp/ReceiptRepositoryOkHttpImpl.java
- sdk-vertx-client/src/main/java/io/nem/symbol/sdk/infrastructure/vertx/ReceiptRepositoryVertxImpl.java
- sdk-vertx-client/src/test/java/io/nem/symbol/sdk/infrastructure/vertx/ReceiptRepositoryVertxImplTest.java
> Transaction statement multiple Recipient Types search support

- CHANGELOG.md
- README.md
- build.gradle
> 0.20.3 release

- integration-tests/src/test/java/io/nem/symbol/sdk/infrastructure/ListenerForTests.java
- sdk-core/src/main/java/io/nem/symbol/sdk/infrastructure/ListenerBase.java
- sdk-core/src/main/java/io/nem/symbol/sdk/infrastructure/ListenerMessage.java
- sdk-core/src/main/java/io/nem/symbol/sdk/model/transaction/JsonHelper.java
- sdk-okhttp-client/src/main/java/io/nem/symbol/sdk/infrastructure/okhttp/JsonHelperGson.java
- sdk-okhttp-client/src/test/java/io/nem/symbol/sdk/infrastructure/okhttp/ListenerOkHttpTest.java
- sdk-vertx-client/src/main/java/io/nem/symbol/sdk/infrastructure/vertx/JsonHelperJackson2.java
- sdk-vertx-client/src/test/java/io/nem/symbol/sdk/infrastructure/vertx/ListenerVertxTest.java
Fixes #273
DO NOT MERGE until rest is merged
> WebSocket payload wrapper.

- sdk-core/src/main/java/io/nem/symbol/sdk/api/Listener.java
- sdk-core/src/main/java/io/nem/symbol/sdk/infrastructure/ListenerBase.java
- sdk-okhttp-client/src/test/java/io/nem/symbol/sdk/infrastructure/okhttp/ListenerOkHttpTest.java
Fixes https://github.com/nemtech/symbol-sdk-java/issues/342
> Unresolved address listener

- CHANGELOG.md
- bootstrap-preset.yml
- bootstrap-start.sh
- integration-tests/src/test/java/io/nem/symbol/sdk/infrastructure/Config.java
- integration-tests/src/test/java/io/nem/symbol/sdk/infrastructure/ListenerForTests.java
- integration-tests/src/test/java/io/nem/symbol/sdk/infrastructure/ListenerIntegrationTest.java
- integration-tests/src/test/java/io/nem/symbol/sdk/infrastructure/ListenerStatusIntegrationTest.java
- integration-tests/src/test/java/io/nem/symbol/sdk/infrastructure/MosaicRepositoryIntegrationTest.java
- integration-tests/src/test/java/io/nem/symbol/sdk/infrastructure/TestHelper.java
- integration-tests/src/test/java/io/nem/symbol/sdk/infrastructure/TransferTransactionIntegrationTest.java
- sdk-core/src/main/java/io/nem/symbol/core/utils/MapperUtils.java
- sdk-core/src/main/java/io/nem/symbol/sdk/api/Listener.java
- sdk-core/src/main/java/io/nem/symbol/sdk/infrastructure/ListenerBase.java
- sdk-core/src/main/java/io/nem/symbol/sdk/infrastructure/ListenerMessage.java
- sdk-core/src/main/java/io/nem/symbol/sdk/infrastructure/ListenerRequest.java
- sdk-core/src/main/java/io/nem/symbol/sdk/model/account/UnresolvedAddress.java
- sdk-core/src/main/java/io/nem/symbol/sdk/model/namespace/NamespaceId.java
- sdk-core/src/main/java/io/nem/symbol/sdk/model/transaction/TransactionStatusError.java
- sdk-core/src/test/java/io/nem/symbol/core/utils/MapperUtilsTest.java
- sdk-okhttp-client/src/main/java/io/nem/symbol/sdk/infrastructure/okhttp/ListenerOkHttp.java
- sdk-okhttp-client/src/main/java/io/nem/symbol/sdk/infrastructure/okhttp/RepositoryFactoryOkHttpImpl.java
- sdk-okhttp-client/src/test/java/io/nem/symbol/sdk/infrastructure/okhttp/ListenerOkHttpTest.java
- sdk-vertx-client/src/main/java/io/nem/symbol/sdk/infrastructure/vertx/ListenerVertx.java
- sdk-vertx-client/src/main/java/io/nem/symbol/sdk/infrastructure/vertx/RepositoryFactoryVertxImpl.java
- sdk-vertx-client/src/test/java/io/nem/symbol/sdk/infrastructure/vertx/ListenerVertxTest.java
It subscribes using aliases if required.
It allows looking for all the unresolved addresses related to an account.
It allows looking for all the unresolved addresses related to an multisig account like cosigners.
Added lots of integration tests.
Improved ListenerBase
FIxes https://github.com/nemtech/symbol-sdk-java/issues/342
> Listener refactoring.
